### ISSUE TITLE
关于DJSRH实验结果

### ISSUE THREAD

**Issue by FutureTwT** [BMC-SDNU/Cross-Modal-Hashing-Retrieval#3]
@zzidlezz DJSRH提供的是Top50 MAP

**Comment by zzidlezz** [comment]
***@***.***呢，这两者有什么区别




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 上午8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[BMC-SDNU/Cross-Modal-Hashing-Retrieval] 关于DJSRH实验结果 (Issue #3)





 
@zzidlezz DJSRH提供的是Top50 MAP
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FutureTwT** [comment]
看一下mAP的计算函数对应一下公式，计算Pre的范围不同

**Comment by zzidlezz** [comment]
您好，请教一下DCHUC这篇文章画PR曲线的代码可以提供一下吗，自己写的总是在曲线的横轴值不到1就无法下降了，看文中PR曲线都可以到横轴为1的地方




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 上午8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 关于DJSRH实验结果 (Issue #3)





 
看一下mAP的计算函数对应一下公式，计算Pre的范围不同
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzidlezz** [comment]
您好，请问您这个跨模态的代码集合中MODEL_DIR = '../models/imagenet-vgg-f.mat'中imagenet-vgg-f.mat这个下载链接可以提供吗，自己下载的里面的格式对不太上。非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 上午8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 关于DJSRH实验结果 (Issue #3)





 
Closed #3.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FutureTwT** [comment]
您可以看一下README

**Comment by zzidlezz** [comment]
***@***.***需要在表格那块单独说明吗，还是说可以直接在表格里列举最好精度是多少。祝您新年快乐！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月9日(星期天) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 关于DJSRH实验结果 (Issue #3)





 
您可以看一下README
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FutureTwT** [comment]
表格是指什么

**Comment by zzidlezz** [comment]
您好，请问可以提供一下IAPR TC-12这个数据集的MAT文件吗，真的很期待您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月20日(星期四) 凌晨2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 关于DJSRH实验结果 (Issue #3)





 
表格是指什么
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzidlezz** [comment]
您好，请问您可以提供一下CMDVH这篇文章的代码吗，非常感谢。DCHUC文中的链接没有找到这个代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "散人"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月7日(星期一) 中午1:31
***@***.***&gt;;

主题:&nbsp;回复： [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 关于DJSRH实验结果 (Issue #3)



您好，请问可以提供一下IAPR TC-12这个数据集的MAT文件吗，真的很期待您的回复




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月20日(星期四) 凌晨2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 关于DJSRH实验结果 (Issue #3)





 
表格是指什么
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
