### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by zzidlezz** [BMC-SDNU/Cross-Modal-Hashing-Retrieval#4]
您好，想请教下CCQ代码里的precision_recall.m这个函数怎么用到主函数里，那个ids参数是什么意思。perf_metric4label.m这个函数算的是最好的map值吗。

**Comment by FutureTwT** [comment]
P/R数值算出后就可以画PR，不是很理解您说的最好map的是啥意思

**Comment by zzidlezz** [comment]
您好，可以提供一下CMDVH这篇文章的代码吗，找了很久都没有找到
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月20日(星期四) 凌晨2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 您好 (Issue #4)





 
P/R数值算出后就可以画PR，不是很理解您说的最好map的是啥意思
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
