### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by zzidlezz** [BMC-SDNU/Cross-Modal-Hashing-Retrieval#5]
您好，请问您可以提供下可以在深度和传统方法下运行的IAPR TC-12数据集么

**Comment by FutureTwT** [comment]
十分抱歉，我这里没有处理好的IAPR TC-12数据集

**Comment by zzidlezz** [comment]
您好，想请问下DCHUC这篇文章里的损失函数||HB-kS||这个式子里的k作为哈希码的长度，但是我发现去掉k能得到更好的精确度，请问这个k有什么意义吗，或者说可以去掉吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 您好 (Issue #5)





 
十分抱歉，我这里没有处理好的IAPR TC-12数据集
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FutureTwT** [comment]
HB在不替换H的情况下（也就是BB^T），此时如果两个样本的相似度是1，那么他们的哈希码按照论文设定应该是完全一致的，也就是内积之和为哈希码长度K，所以K是为了缩放S的量纲到[-K,K]。至于去掉之后效果好，我认为是如果不放大S的量纲，相当于缩小了HB结果的量纲，但是并不会影响正负性，所以学习到的哈希码还是差不多的，并且更小的数值可能有助于算法的收敛过程。

**Comment by zzidlezz** [comment]
非常感谢您的回复，对我的帮助很大.请问这个式子的设计是一直这样沿用吗，比如说我去掉k效果好我可以去掉吗，或者说更改前后两项的系数.我可以理解为两个哈希码的内积不一定非要对应后面的值的区间吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FutureTwT ***@***.***&gt;
发送时间: 2022年3月6日 17:41
收件人: BMC-SDNU/Cross-Modal-Hashing-Retrieval ***@***.***&gt;
抄送: zzidlezz ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 您好 (Issue #5)





 
HB在不替换H的情况下（也就是BB^T），此时如果两个样本的相似度是1，那么他们的哈希码按照论文设定应该是完全一致的，也就是内积之和为哈希码长度K，所以K是为了缩放S的量纲到[-K,K]。至于去掉之后效果好，我认为是如果不放大S的量纲，相当于缩小了HB结果的量纲，但是并不会影响正负性，所以学习到的哈希码还是差不多的，并且更小的数值可能有助于算法的收敛过程。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FutureTwT** [comment]
有的论文是加了的，有的论文没加，个人认为加不加都可以，毕竟不影响正负性，而sign过程只关心正负而不关心具体数值大小

**Comment by zzidlezz** [comment]
非常感谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 上午9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 您好 (Issue #5)





 
有的论文是加了的，有的论文没加，个人认为加不加都可以，毕竟不影响正负性，而sign过程只关心正负而不关心具体数值大小
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzidlezz** [comment]
您好，我想请问下在您的跨模态基线方法合集中的SSAH方法您那边可以跑出结果吗，我用您提供的数据集跑这个方法，loss的损失结果全都是nan，精度无法保持不变无法被优化，被这个问题困扰了很久，期待您的解答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月6日(星期天) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 您好 (Issue #5)





 
HB在不替换H的情况下（也就是BB^T），此时如果两个样本的相似度是1，那么他们的哈希码按照论文设定应该是完全一致的，也就是内积之和为哈希码长度K，所以K是为了缩放S的量纲到[-K,K]。至于去掉之后效果好，我认为是如果不放大S的量纲，相当于缩小了HB结果的量纲，但是并不会影响正负性，所以学习到的哈希码还是差不多的，并且更小的数值可能有助于算法的收敛过程。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FutureTwT** [comment]
我记得之前测试的时候也遇到过nan的问题，似乎在COCO上更常见，不过后来经过调参等过程，似乎解决了

**Comment by zzidlezz** [comment]
您好，可以说明的再详细一些吗，比如调参是调学习率这些参数吗？很需要这篇代码的结果比较，麻烦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMC-SDNU/Cross-Modal-Hashing-Retrieval"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 凌晨1:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMC-SDNU/Cross-Modal-Hashing-Retrieval] 您好 (Issue #5)





 
我记得之前测试的时候也遇到过nan的问题，似乎在COCO上更常见，不过后来经过调参等过程，似乎解决了
